### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by seven1m** [churchio/onebody#216]
(in addition to MySQL)

**Comment by seven1m** [comment]
@aunderwo would like to help with this... Let's try to get this merged in soon...

**Comment by aunderwo** [comment]
If I can be of any help, please get in touch. I have a reasonable amount of RoR experience but will need a little guidance with testing

**Comment by aunderwo** [comment]
There are a few other mysql specific queries, e.g in search
https://github.com/churchio/onebody/blob/master/app/models/search.rb#L145-155
These will be hard to make database agnostic. In mqsql and postgresql we can use instead of:
month(people.birthday)
SELECT EXTRACT(MONTH FROM people.birthday);
However in SQLITE there is no EXTRACT function, would have to use SELECT STRFTIME('%m', people.birthday) which doesn't exist in postgresql or mysql.
Should we try to be fully DB agnostic or just go with 'grown up' databases. In some ways it may be nice to use SQLITE since it lowers the development barrier but maybe it's too much of an ask to make all the code compatible. 
Any comments?

**Comment by aunderwo** [comment]
Great stuff. :+1:
 Couple of questions re testing. 
1) Does Travis-ci test against both mysql and postgresql databases?
2) when running rspec locally should we ideally have both mysql and postgresql locally and run rspec twice

**Comment by seven1m** [comment]
Travis tests both, yes. So cool!

I wouldn't expect anyone to run both dbs locally unless that dev is doing some major SQL hacking (which I would discourage anyway). We'll rely on Travis to catch bugs that crop up.
