### ISSUE TITLE
Geocoder::ConfigurationError (The Mapquest World API requires a key to be configured: "key")

### ISSUE THREAD

**Issue by shawnpyle** [churchio/onebody#425]
I just deployed a OneBody to DigitalOcean. The droplet failed to install fully but I managed to work through the manual setup (good documentation!) to get most everything working. However, I'm getting the following error when adding/updating addresses.

    Geocoder::ConfigurationError (The Mapquest World API requires a key to be configured: "key"):
    app/models/updater.rb:116:in `save!'
    app/controllers/people_controller.rb:125:in `update

Is this likely related to issue #347 ? If so, do we need to register ourselves?

**Comment by seven1m** [comment]
@shawnpyle, sorry about your trouble installing on D.O. I'm working on a fix for that.

Since you did the install manually, I'm guessing you copied the `config/secrets.yml.example` file the `master` branch, which is after we switched to Google geocoder. Anyway, long story short, I think you should change your `config/secrets.yml` to look like https://github.com/churchio/onebody/blob/254bd0374466fc4e4ea0005d145ebbb4ee33f576/config/secrets.yml.example so it has a mapquest api key.

**Comment by seven1m** [comment]
@shawnpyle I just fixed the install issue on Digital Ocean. So if you'd rather kill your current droplet and start over, you can!

**Comment by shawnpyle** [comment]
Botabing! It now works. Thanks for your work and pointing me to the right solution!

**Comment by seven1m** [comment]
:smile_cat:

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://www.orangecountytacoguy.com/election.php?i8>

 

klaus@hebsgaard.dk
