### ISSUE TITLE
Deleting a member errors in production

### ISSUE THREAD

**Issue by buob** [churchio/onebody#574]
```
App 6353 stderr: Errno::EACCES (Permission denied @ unlink_internal - /var/www/onebody/public/system/production/people/photos/125/original/aac7d21ab24480baf2b3cf02bc09baa0.jpg):
App 6353 stderr:   app/models/person.rb:237:in `block in destroy'
App 6353 stderr:   app/models/person.rb:236:in `destroy'
App 6353 stderr:   app/models/family.rb:219:in `destroy'
App 6353 stderr:   app/controllers/families_controller.rb:98:in `destroy'
```

This probably has more to do with my deploy/server settings (Phusion passenger with apache, via the provision.sh), but in case anyone else runs into this, thought it'd be helpful to document.

**Comment by hunternet93** [comment]
After poking around for a bit, I found [this article](https://www.phusionpassenger.com/library/admin/apache/troubleshooting/ruby/#the-rails-application-reports-that-it-s-unable-to-start-because-of-a-permission-error) that states that when run from Apache, Passenger starts as the user owning the app's config.ru, or as nobody if config.ru is owned by root. Changing config.ru's owner to www-data solved the problem.

**Comment by buob** [comment]
Perfect, thanks for the help @hunternet93, I'll submit a PR soon with adding that stuff to the provision.sh

**Comment by buob** [comment]
OR, you could just run the following, https://github.com/buob/onebody/commit/04f0ad66ec13c4e45caf7a11bf38ba88414978a6#diff-7595fa4e138468240ded70de1ec4ee34R39, which is in the manual install that I missed.
