### ISSUE TITLE
Error in 3.7.0 when generate report.

### ISSUE THREAD

**Issue by jairbj** [churchio/onebody#661]
I just installed v3.7.0, added some data and when I tried to generate some reports (/admin/reports) I have this screen for the 3 kinds of report available.

![temp](https://cloud.githubusercontent.com/assets/1747830/23918496/ef70acd0-08d1-11e7-81fd-a7615d0c3c9a.png)

**Comment by jairbj** [comment]
Hi friend, I checked that this error occurs because of the dossier.yml file. According to the "dossier" gem documentation it needs to have the content of database.yml or a symbolic link. I copied my database.yml into the dossier.yml and the reports worked. I'm new to ruby/rails and I don't  figure out if it's possible to "import" one yml file into another to solve this issue.

**Comment by seven1m** [comment]
@jairbj thanks for this report! I just checked on an instance of OneBody upgraded from 3.6.0 to 3.7.0 and the dossier.yml file is present and there is no error.

How did you install OneBody? How did you upgrade?

The fix is, as you said, to symlink dossier.yml to database.yml, but that should be automatic with an upgrade.

**Comment by jairbj** [comment]
Hi, I made a manual fresh install on windows. I cloned github, created a
branch based on 3.7.0 release and followed the readme instructions.

**Comment by seven1m** [comment]
@jairbj sorry it took me awhile on this one. I realized that this file is a symlink and on Windows it isn't supported. So I added instructions in cbb2a60a76b46d44551054940c2ccf81fa51132a just now to copy `database.yml` to `dossier.yml`.
